---
abstract: 'Manage Windows Services'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-ServiceManager
requires:
  IPC::System::Simple: 1.21
  Moo: 1.000007
  Test::Deep: 0.110
resources:
  repository: git://github.com/frioux/Win32-ServiceManager.git
version: 0.001001
